cursor #e7e2dd
cursor_text_color #cac6c1

foreground            #e7e2dd
background            #141311
selection_foreground  #343024
selection_background  #cec6b4
url_color             #d1c6ab

color0   #141311
color1   #f0776c
color2   #77d168
color3   #ffe772
color4   #c6ba9b
color5   #605740
color6   #d1c6ab
color7   #dbd7ce
color8   #87847d
color9   #ffa79f
color10  #affaa3
color11  #fff0a5
color12  #e5dbc2
color13  #fff5de
color14  #fff8ea
color15  #fffdf8
